# Generated by Django 6.0.4 on 2026-05-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#6c757d', max_length=7, verbose_name='Цвет'),
        ),
    ]
