# Generated by Django 6.0.5 on 2026-05-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answerlike',
            options={'verbose_name': 'Реакция на ответ', 'verbose_name_plural': 'Реакции на ответ'},
        ),
        migrations.AlterModelOptions(
            name='questionlike',
            options={'verbose_name': 'Реакция на вопрос', 'verbose_name_plural': 'Реакции на вопрос'},
        ),
        migrations.AddField(
            model_name='answerlike',
            name='value',
            field=models.SmallIntegerField(choices=[(1, 'Лайк'), (-1, 'Дизлайк')], verbose_name='Оценка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionlike',
            name='value',
            field=models.SmallIntegerField(choices=[(1, 'Лайк'), (-1, 'Дизлайк')], verbose_name='Оценка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answerlike',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата реакции'),
        ),
        migrations.AlterField(
            model_name='questionlike',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата реакции'),
        ),
    ]
