# Generated by Django 6.0.4 on 2026-05-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_alter_answerlike_options_alter_questionlike_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerlike',
            name='value',
            field=models.SmallIntegerField(choices=[(1, 'Лайк'), (-1, 'Дизлайк')], verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='questionlike',
            name='value',
            field=models.SmallIntegerField(choices=[(1, 'Лайк'), (-1, 'Дизлайк')], verbose_name='Оценка'),
        ),
    ]
