upstream django_app { server web:8000; }
proxy_cache_path /var/cache/nginx keys_zone=django_cache:10m inactive=60m;

server {
    listen 80;
    
    location /uploads/ {
        alias /app/uploads/;
        expires 30d;
        add_header Cache-Control "public";
    }
    
    location /static/ {
        alias /app/static/;
        expires 30d;
        add_header Cache-Control "public";
        add_header X-Cache-Status "STATIC";
    }
    
    location / {
        proxy_pass http://django_app;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_cache django_cache;
        proxy_cache_valid 200 10m;
        add_header X-Cache-Status $upstream_cache_status;
    }
}